spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ECOM
    username: {Your username. Dont Use root. Use different username}
    password: {Your password}
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect